alter table public.profiles enable row level security;alter table public.facilities enable row level security;alter table public.booking_settings enable row level security;alter table public.courts enable row level security;alter table public.bookings enable row level security;alter table public.payments enable row level security;alter table public.blocked_times enable row level security;alter table public.admin_audit_log enable row level security;
create or replace function public.is_admin(uid uuid) returns boolean language sql stable security definer set search_path=public as $$select coalesce((select raw_user_meta_data->>'role'='admin' from auth.users where id=uid),false)$$;
create policy if not exists "active facilities" on public.facilities for select using(is_active);
create policy if not exists "public settings" on public.booking_settings for select using(true);
create policy if not exists "active courts" on public.courts for select using(is_active);
create policy if not exists "own profile" on public.profiles for select using(id=auth.uid());
create policy if not exists "own bookings" on public.bookings for select using(user_id=auth.uid() or public.is_admin(auth.uid()));
create policy if not exists "own payments" on public.payments for select using(exists(select 1 from public.bookings b where b.id=booking_id and (b.user_id=auth.uid() or public.is_admin(auth.uid()))));
create policy if not exists "admin courts" on public.courts for all using(public.is_admin(auth.uid())) with check(public.is_admin(auth.uid()));
create policy if not exists "admin settings" on public.booking_settings for all using(public.is_admin(auth.uid())) with check(public.is_admin(auth.uid()));
create policy if not exists "admin blocks" on public.blocked_times for all using(public.is_admin(auth.uid())) with check(public.is_admin(auth.uid()));
create policy if not exists "admin audit" on public.admin_audit_log for select using(public.is_admin(auth.uid()));